"""empty message

Revision ID: 12c6aed276d7
Revises: 8320899f974c
Create Date: 2018-10-12 14:33:32.649937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12c6aed276d7'
down_revision = '8320899f974c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('i_avatar', sa.String(length=128), nullable=True))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'i_avatar')
    # ### end Alembic commands ###
