"""empty message

Revision ID: 391a5162a981
Revises: 9f3050d96692
Create Date: 2018-08-21 14:07:57.718621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391a5162a981'
down_revision = '9f3050d96692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
