"""empty message

Revision ID: 43808891f9a5
Revises: 5ae60555b391
Create Date: 2018-08-16 14:18:38.096517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43808891f9a5'
down_revision = '5ae60555b391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_create_time'), 'posts', ['create_time'], unique=False)
    op.drop_index('ix_posts_timestamp', table_name='posts')
    op.drop_column('posts', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.create_index('ix_posts_timestamp', 'posts', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_posts_create_time'), table_name='posts')
    op.drop_column('posts', 'create_time')
    # ### end Alembic commands ###
