"""empty message

Revision ID: 52e5125df703
Revises: e24a32935aae
Create Date: 2018-09-06 16:42:39.364835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e5125df703'
down_revision = 'e24a32935aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anwsers', sa.Column('replier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'anwsers', 'questions', ['replier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'anwsers', type_='foreignkey')
    op.drop_column('anwsers', 'replier_id')
    # ### end Alembic commands ###
